name: marmangam

on:
  workflow_dispatch:
  issues:
    types: [opened]
  project_card:
    types: [moved]

jobs:
  issue_project:
    runs-on: ubuntu-latest

    steps:
      - name: Acción de GitHub Script
        uses: actions/github-script@v6  
        with:
          script: |
            const payload = context.payload;
            const issue = payload.issue;
            const action = payload.action;

            if (issue) {
              console.log(`El issue con ID ${issue.id} ha sido ${action}`);
              return `El issue fue procesado con éxito.`;
            } else {
              console.log(`No hay un issue en este evento (${context.eventName})`);
              return `Evento sin issue: ${context.eventName}`;
            }
            
      - name: Info del issue y del proyecto
        run: |
          echo "Evento que disparó el flujo: ${{ github.event_name }}"
          echo "Estado del Issue: ${{ github.event.action }}"
           if [ "${{ github.event.issue.title }}" != "" ]; then
            echo "Título del issue: ${{ github.event.issue.title }}"
          else
            echo "No hay issue en este evento."
          fi
          
      
